{

  programs.bash = {
    enable = true;
    bashrcExtra = ''
      function rebuild() {
        pushd /home/nix-shared
        git add *
        home-manager switch --flake /home/nix-shared#babbabra
        git add *
        git commit -m "autogenerated commit message"
        popd
      }
    '';
  };

}
