{
  programs.bash = {
    enable = true;
    shellAliases = {
      gc = "sudo nix-collect-garbage -d";
      sd = "shutdown 0";
      rb = "reboot";
      pic = "kitty icat";
    };
    bashrcExtra = ''
      function rebuild() {
        pushd ~/nix
        git add *

        status=$(git status)

        nixos=$(echo "$status" | grep 'nixos')
        home=$(echo "$status" | grep 'home')
        config=$(echo "$status" | grep 'configuration')
        flake=$(echo "$status" | grep 'flake')

        if [ -n "$home" ]
          then
            home-manager switch --flake ~/nix#tobi
        fi
        if [ -n "$nixos" -o -n "$config" ]
            then
              sudo nixos-rebuild switch --flake ~/nix#tobi
        fi
        if [ -n "$flake" ]
            then
              nix flake update
        fi

        # in case hardware-configuration.nix changes or something
        git add *

        if [ "$1" == "-c" ]
          then
            if [ -n "$2" ]
              then
                msg=""
                for i in "''${@:2}"
                  do
                    msg="$msg $i"
                done
                git commit -m "$msg"
              else
                git commit -m "autogenerated commit message"
            fi
            git push origin main
          else
            echo "You are not committing the changes. Please use
            >    git commit -m [message]"
        fi
        popd
      }

      function mkcd() {
        mkdir $1
        cd $1
      }

      export STARSHIP_CONFIG="$HOME/.config/starship.toml"
      eval "$(starship init bash)"
    '';
  };
}
