{
  programs.bash = {
    enable = true;
    shellAliases = {
      sd = "shutdown 0";
      rb = "reboot";
      pic = "kitty icat";
      ls = "eza --color=always --icons=always";
      tree = "eza -T --color=always --icons=always";
      lg = "lazygit";
#     add = "git add *";
#     commit = "git commit -m \"autogenerated commit message\"";
#     push = "git push origin main";
    };
    bashrcExtra = ''
      function rebuild() {
        pushd ~/nix
        git add *

        status=$(git status)

        nixos=$(echo "$status" | grep 'nixos')
        home=$(echo "$status" | grep 'home')
        config=$(echo "$status" | grep 'configuration')
        flake=$(echo "$status" | grep 'flake')

        if [ -n "$home" ]
          then
            home-manager switch --flake ~/nix#tobi
        fi
        if [ -n "$nixos" -o -n "$config" ]
            then
              sudo nixos-rebuild switch --flake ~/nix#tobi
        fi
        if [ -n "$flake" ]
            then
              nix flake update
        fi

        # in case hardware-configuration.nix changes or something
        git add *

        if [ "$1" == "-c" ]
          then
            if [ -n "$2" ]
              then
                msg=""
                for i in "''${@:2}"
                  do
                    msg="$msg $i"
                done
                git commit -m "$msg"
              else
                git commit -m "autogenerated commit message"
            fi
            git push origin main
          else
            echo "You are not committing the changes. Please use
            >    git commit -m [message]"
        fi
        popd
      }

      function gc() {
        home-manager expire-generations "-7 days"
        sudo nix-collect-garbage -d
      }

      function mkcd() {
        mkdir $1
        cd $1
      }

      function update() {
        pushd ~/nix
        nix flake update
        popd
        rebuild -c
      }

      function shell() {
        export ORIGINAL_DIR=$(pwd)
        pushd ~/nix
        nix develop .#$1
        popd
        unset ORIGINAL_DIR
      }

      export _ZO_DOCTOR=0
      eval "$(zoxide init bash)"

      export STARSHIP_CONFIG="$HOME/.config/starship.toml"
      eval "$(starship init bash)"
    '';
  };
}
