{

  programs.bash = {
    enable = true;
    shellAliases = 
    let
      flakePath = "~/nix";
    in {
      rbnixos = "sudo nixos-rebuild switch --flake ${flakePath}#tobi";
      rbhome = "home-manager switch --flake ${flakePath}#tobi";
      rbflake = "nix flake update";

      gc = "sudo nix-collect-garbage -d";
      sd = "shutdown 0";
    };
    bashrcExtra = ''
      function rebuild() {
        git add *

        status=$(git status)

        nixos=$(status | grep 'nixos')
        home=$(status | grep 'home')
        config=$(status | grep 'configuration')
        flake=$(status | grep 'flake')

        if [ -n $home ]
          then
            home-manager switch --flake ~/nix#tobi
        fi
        if [ -n $nixos || -n $config ]
            then
              sudo nixos-rebuild switch flake ~/nix#tobi
        fi
        if [ -n $flake ]
            then
              nix flake update
        fi

        # in case hardware-configuration.nix changes or something
        git add *

        if [ $1 == "-c" ]
          then
            if [ -n $2 ]
              then
                git commit -m "autogenerated commit message"
              else
                git commit -m $2
            fi
            read -p "Do you want to push? (y/n)" push
            if [ $push == "y" ]
              then
                git push origin main
            fi
          else
            echo "You are not committing the changes. Please use
            >    git commit -m [message]"
        fi
      }
    '';
  };

}
